In [124]:
import pandas as pd
import numpy as np
import re

In [125]:
df = pd.read_csv('/content/SMSSpamCollection.txt', sep='\t', names=['Output', 'Text'])
df.head()

  Output                                               Text
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [126]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [127]:
from nltk.corpus import stopwords
words = stopwords.words('english')

In [128]:
import warnings
warnings.filterwarnings('ignore')

In [129]:
import nltk
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [130]:
from nltk.stem import WordNetLemmatizer
stemms = WordNetLemmatizer()

In [134]:
corous = []
for i in range(len(df['Text'])):
  df['Text'][i] = re.sub('[^a-zA-Z]', ' ', df['Text'][i])
  df['Text'][i] = (df['Text'][i]).lower()
  df['Text'][i] = df['Text'][i].split()
  df['Text'][i] = [stemms.lemmatize(word) for word in df['Text'][i] if word not in set(words)]
  df['Text'][i] = ' '.join(df['Text'][i])
  corous.append(df['Text'][i])

In [140]:
from sklearn.feature_extraction.text import TfidfVectorizer
x = TfidfVectorizer().fit_transform(corous).toarray()
y = pd.get_dummies(df['Output'])
y = y.iloc[:, 1].values

In [141]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [144]:
from sklearn.naive_bayes import MultinomialNB
cv = MultinomialNB()
cv.fit(x_train, y_train)
y_pred = cv.predict(x_test)

In [146]:
from sklearn.metrics import confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))
print(accuracy_score(y_test, y_pred))

[[965   1]
 [ 31 118]]
0.9713004484304932

In [132]:
df.head()

  Output                                               Text
0    ham  go jurong point crazy available bugis n great ...
1    ham                            ok lar joking wif u oni
2   spam  free entry wkly comp win fa cup final tkts st ...
3    ham                u dun say early hor u c already say
4    ham                nah think go usf life around though

In [133]:
l = ['sahil', 'jal']
l = ' '.join(l)
l

'sahil jal'